### ISSUE TITLE
Why does the boot0-header definition is sligtly different from sunxi's official definition?

### ISSUE THREAD

**Issue by bittervan** [Ouyancheng/FlatHeadBro#1]
Thank you a lot for your work! I learned from your repository. But I found that the boot0-header definition differs from SUNXI's official one as illustrated in https://linux-sunxi.org/EGON. Is there any customized modification because this is a RISC-V chip?

The official one says that the BT0 is something like this
<img width="215" alt="image" src="https://user-images.githubusercontent.com/57927141/225814665-05ffc16d-cdd6-43b8-89d2-e5fc7404fc24.png">

But the definition in your repo is 

``` c
/******************************************************************************/
/*                              file head of Boot                             */
/******************************************************************************/
typedef struct _Boot_file_head {
    uint32_t  jump_instruction;   /* one intruction jumping to real code */
    uint8_t   magic[MAGIC_SIZE];  /* ="eGON.BT0" */
    uint32_t  check_sum;          /* generated by PC */
    uint32_t  length;             /* generated by PC */
    uint32_t  pub_head_size;      /* the size of boot_file_head_t */
    uint8_t   pub_head_vsn[4];    /* the version of boot_file_head_t */
    uint32_t  ret_addr;           /* the return value */
    uint32_t  run_addr;           /* run addr */
    uint32_t  boot_cpu;           /* eGON version */
    uint8_t   platform[8];        /* platform information */
} boot_file_head_t;
```

And because of my lack of embedded system development experience, I cannot find a similar definition in the official u-boot repository https://github.com/smaeul/u-boot. So could you please tell me where did you get the public header layout?

**Comment by Ouyancheng** [comment]
Hi @bittervan, 
Sorry for the late. I try to remember where I took this header from and it was likely from here: https://github.com/smaeul/sun20i_d1_spl/blob/mainline/include/private_boot0.h 

Nonetheless, by experiment, it seems like only the fields up to public header size are required to boot it up, the rest doesn't seem to matter. 

Please refer to https://github.com/Ouyancheng/FlatHeadBro/blob/master/boot0/include/boot0-header.h for a simplified header. 

Thanks for the question though!

**Comment by bittervan** [comment]
Thanks, this is very helpful for a newbie like me!
